### ISSUE TITLE
API cannot fetch Latest forge build.

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [TheRandomLabs/CurseAPI-Minecraft#1]
Using the Changelog Generator by you guys, and it spits this error

com.therandomlabs.curseapi.minecraft.forge.InvalidForgeVersionException: Invalid Forge version: 1.12.2-14.23.4.2766

Im assumbing the bot stoped working because its not picking up a thing

**Comment by TheRandomLabs** [comment]
Just for the record, TheRandomLabs is my online alias, not an organization.

What version of ChangelogGenerator are you using? CurseAPI-Minecraft is loading the changelog for build 2766 fine on my end.

**Comment by CrankySupertoonArchive** [comment]
I think 1.10.3

**Comment by TheRandomLabs** [comment]
This was fixed in 1.11. Next time, you should check for a newer version before reporting an issue.
